[window]
padding = {x = 8, y = 8}
opacity = 0.8
decorations = "Transparent"

[font]
size = 16.0
normal = { family = "Mononoki Nerd Font", style = "Regular"}
bold = { family = "Mononoki Nerd Font", style = "Bold"}
italic = { family = "Mononoki Nerd Font", style = "Italic"}
bold_italic = { family = "Mononoki Nerd Font", style = "Bold Italic"}

